@startuml
package "nolang" {
    class Main {}
    class AlgebraicRunner {}
    class DynamicTypedRunner {}
    class StaticTypedRunner {}

}

package "nolang.common" {
    interface Type{
       + accepts(Value): boolean
    }
    record IntType
    record RealType
    record BoolType
    record VoidType

}
package "nolang.common.values" {
    interface Returned {
    +match(onNumeric, onBool, onVoid): T
    }
      interface NumericValue {}

    record IntValue
    record BoolValue
    record VoidValue
    record RealValue

}


package "nolang.common.core" {
    interface Either<L,R>{
        left()
        right()
        fold()
        isLeft()
        isRight()
        map()
        flatMap()
        orElse()
        orElseGet()
        leftOptional()
        rightOptional()
    }
    record Left
    record Right


    interface Eval{}
    record Environment

    Eval ..> Result : returns
    Eval ..> Environment : uses

    interface Result<A>{
        + environment: Environment
        + value: A
    }
    record Returned
    record Interrupted

    Result <|.. Returned
    Result <|.. Interrupted

    interface InterruptReason{}
    record Control {
        + signal
    }
    record Error{
        + error
    }

    interface EvalControl{
    }
    record Break
    record Continue
    record Return

    EvalControl <|.. Break
    EvalControl <|.. Continue
    EvalControl <|.. Return

    interface EvalError{}
    record SyntaxError
    record ArithmeticError
    record TypeError
    record ArityError

    EvalError <|.. SyntaxError
    EvalError <|.. ArithmeticError
    EvalError <|.. TypeError
    EvalError <|.. ArityError



    record Function {
        signature: FunctionSignature
        body: FunctionBody
        closureScope: Scope
        helpText: String
        call(args): Eval<Value>
    }

    record FunctionSignature{
        +name()
        +parameters()
        +returnType()
        +arity():Arity
    }

    record Scope{}

    interface FunctionBody{}

    record FunctionRegistry{}
    FunctionRegistry o-- Function
    Function --> FunctionSignature
    Function --> FunctionBody
    Function --> Scope
    Function ..> Eval : returns


    interface ScopeError{}
    record UndefinedVariable
    record DuplicatedVariable
    record UninitializedVariable
    record UndefinedFunction

    class Arity{}



    enum Unit{}

    interface Declaration{ }
    record Variable
    record FunctionDeclaration
    record FunctionParameter{
        +accepts(Value value): boolean
        }

}



package "nolang.common.combinators" {
    class BuiltInFunctions{
     + create(): Map<String, Function>
    }

    class Folds{
    +left(): NumericValue
    +right(): NumericValue
    +right(): NumericValue
    +foldLeftNumeric(): Eval<NumericValue>
    +foldLeftAssociativeNumeric(): Eval<NumericValue>
    +foldLeftDynamic(): Eval<Returned>
    +collectArguments(): Eval<List<Returned>>
    }
    class ScopeCombinators{}

    class ValueParser{
    +parseNumber(): Eval<NumericValue>
    +parseBoolean(): Eval<Value.Bool>
    }

    class NumericValues {
        + narrow(Value value): Eval<NumericValue>
    }

    class EnvironmentCombinators{
        +callFunction(): Eval<Returned>
        +getEnvironment(): Eval<Environment>
        +modifyEnvironment(): Eval<Unit>
    }

}


package "nolang.common.operations" {
    interface "BinaryOperation<T>"{
    + operator(): String
    + apply(T left, T right): Eval<T>
    + {default} apply(Eval<T>left,Eval<T>right): Eval<T>
    }
    interface "RelationOperation<L, R>"
    {
    + operator(): String
    + apply(Eval<L> left, Eval<R> right): Eval<Value.Bool>
    + {default} apply(Eval<L> left, Eval<R> right): Eval<Value.Bool>
    }
    interface "UnaryOperation<T>" {
    + operator(): String
    + apply(T operand): Eval<T>
    + {default} apply(Eval<T>operand): Eval<T>
    }

    enum UnaryLogicalOperation{}
    enum UnaryNumericOperation{}
    enum NumericComparisonOperation{}
    enum BinaryLogicalOperation{}
    enum BinaryNumericOperation{}
    class Logical{}
    class Numeric{}


}

package "nolang.algebraic" {
class AlgebraicEvalVisitor{}
class AlgebraicInterpreter{}
class AlgebraicSyntaxAnalyzer{}

}
    Type <|.. IntType
    Type <|.. RealType
    Type <|.. BoolType
    Type <|.. VoidType

    Type ..> Returned : uses
    BuiltInFunctions ..> Type : uses
    Declaration ..> Type : uses
    FunctionSignature ..> Type : uses

    EvalError <|-- ScopeError

    ScopeError <|.. UndefinedVariable
    ScopeError <|.. DuplicatedVariable
    ScopeError <|.. UninitializedVariable
    ScopeError <|.. UndefinedFunction

    Either <|.. Left
    Either <|.. Right

    Scope ..> Either : returns
    Scope ..> Scope : uses
    Scope ..> ScopeError : uses
    Scope ..> Returned : uses

    FunctionRegistry ..> Eval : uses
    FunctionRegistry ..> FunctionSignature : uses
    FunctionRegistry ..> FunctionBody : uses
    FunctionRegistry ..> Scope : uses

    Environment ..> FunctionRegistry : uses
    Environment ..> Scope : uses

    Eval ..> EvalError : uses
    Eval ..> Environment : uses
    Eval ..> Result : returns

    UserDefined ..> Result : returns

    Folds ..> NumericValues : uses
    BuiltInFunctions ..> EnvironmentCombinators : uses
    BuiltInFunctions ..> Arity : uses
    BuiltInFunctions ..> FunctionParameter : uses
    ScopeCombinators ..> EnvironmentCombinators : uses
    FunctionParameter ..> Returned : uses

    EnvironmentCombinators ..> Eval : returns
    EnvironmentCombinators ..> Result : uses


    FunctionBody ..> Eval : returns
    ValueParser ..> Eval : returns
    EnvironmentCombinators ..> Unit : returns
    ScopeCombinators ..> Eval : returns
    Folds ..> Eval : returns
    Folds ..> NumericValue : returns

    "UnaryOperation<T>" <|.. UnaryLogicalOperation : UnaryOperation<Value.Bool>
    "UnaryOperation<T>" <|.. UnaryNumericOperation : UnaryOperation<NumericValue>
    "RelationOperation<L, R>" <|.. NumericComparisonOperation : RelationOperation<NumericValue, NumericValue>
    "BinaryOperation<T>" <|.. BinaryLogicalOperation : BinaryOperation<Value.Bool>
    "BinaryOperation<T>" <|.. BinaryNumericOperation : BinaryOperation<NumericValue>

    UnaryLogicalOperation ..> Logical : uses
    UnaryNumericOperation ..> Numeric : uses
    NumericComparisonOperation ..> Numeric : uses
    BinaryLogicalOperation ..> Logical : uses
    BinaryNumericOperation ..> Numeric : uses

    Logical ..> Eval : returns Eval<Value.Bool>
    Numeric ..> Eval : returns Eval<NumericValue>

    NumericValue <|-- IntValue
    NumericValue <|-- RealValue
    Returned <|.. NumericValue
    Returned <|-- BoolValue
    Returned <|-- VoidValue

    BuiltIn ..> EnvironmentCombinators : uses
    UserDefined ..> EnvironmentCombinators : uses

    FunctionSignature --> FunctionParameter : parameters
    FunctionSignature --> Arity : arity
    FunctionSignature --> Type : returnType

    Declaration <|.. FunctionParameter

    BuiltIn ..> Unit : returns

    AlgebraicEvalVisitor ..> EnvironmentCombinators : uses

    AlgebraicRunner ..> BuiltInFunctions : uses
    AlgebraicRunner ..> AlgebraicInterpreter : uses
    AlgebraicRunner ..> Result : returns


    AlgebraicInterpreter ..> AlgebraicSyntaxAnalyzer : uses
    AlgebraicInterpreter ..> Result : returns

package "nolang.dynamic_typed" {
'planned
}
package "nolang.static_typed" {
'planned
}

@enduml
